# Generated by Django 3.0.4 on 2021-04-21 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={},
        ),
        migrations.RemoveField(
            model_name='data',
            name='base_id',
        ),
        migrations.RemoveField(
            model_name='data',
            name='error_text',
        ),
        migrations.RemoveField(
            model_name='data',
            name='fon_id',
        ),
        migrations.RemoveField(
            model_name='data',
            name='status',
        ),
        migrations.RemoveField(
            model_name='data',
            name='time',
        ),
    ]
