# Generated by Django 3.0.4 on 2021-04-21 11:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210421_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name': 'Запись', 'verbose_name_plural': 'Хранилище записей'},
        ),
        migrations.AddField(
            model_name='data',
            name='base_id',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='data',
            name='error_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='data',
            name='fon_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='data',
            name='status',
            field=models.CharField(choices=[('w', 'Ожидает отправки'), ('d', 'Отправлен'), ('s', 'Успешно сохранен'), ('e', 'Ошибка')], default='w', help_text='Статус записи', max_length=1),
        ),
        migrations.AddField(
            model_name='data',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
